import Foundation

/// Rumor Woods 2026 logon/logoff and death broadcast phrases (player
/// name and gendered pronouns removed, leaving the longest distinctive
/// flavor fragment to match on). Sourced from gswiki:
///   Rumor_Woods/2026_logphrase_customizations
///   Rumor_Woods/2026_death_customizations
/// plus the default (non-custom) arrival/departure/linkdeath phrases.
/// Used by `LogClassifier` to bucket these single-line broadcasts so the
/// log viewer can hide them. Regenerate from those pages each year.
enum LogPhraseCatalog {
    static let logon: [String] = [
        "A chorus of distant howls marks the arrival of",
        "A chorus of feral wails signals the departure of",
        "A faint whiff of tea and citrus precedes the arrival of",
        "A pair of knitting needles drops to the ground as",
        "Amid a brief squall of autumn-kissed leaves",
        "Amid a cascade of mauve myrtle blossoms",
        "Amid the alignment of numerology",
        "An army of whirring and clanking automatons escort",
        "Arriving amidst the scent of fresh cut grass",
        "As if blown free of a myrtle tree, mauve petals dance across the ground, marking the departure of",
        "At the sound of a bosun's whistle",
        "Blades of fresh cut grass herald the arrival of",
        "Blades of fresh cut grass herald the departure of",
        "Brow furrowed in concentration",
        "Darkness descends upon",
        "Distant, predatory howls are a precursor to",
        "Drawing a piece of chalk from",
        "Dusting chalk from",
        "Ecclesiastical chorus sing on high as",
        "Foul and gaseous, the scent of low tide wafts through the air moments before",
        "Glittering golden sand drifts in on a warm breeze, heralding the arrival of",
        "Golden sands herald the arrival of",
        "Golden sands obscure",
        "Haloed in a beam of warm, golden light",
        "Leaving behind a trail of rapidly melting crystalline snowflakes",
        "Like a sudden winter squall",
        "Mauve petals cascade across the ground, marking the arrival of",
        "Murmuring something about needing sleep",
        "Raucous catcalls let you know that",
        "Scribing mathematical equations in the air",
        "Shrouded in inky blackness",
        "Swirling golden sand spirals around",
        "The scent of low tide lets you know",
        "Tumbling upon the ground, several autumn leaves mark the arrival of",
        "Turning blurry eyes to the distance",
        "Whirring and clanking noises precede the arrival of",
        "With a lazy stretch and broad yawn",
        "Within a halo of warm, golden light",
        "Yawning broadly",
        "arrives amid a light flurry of crystalline snowflakes",
        "arrives with a wide yawn and carefully begins picking straw from",
        "arrives, followed by an army of whirring and clanking automatons",
        "bows with a flourish and departs",
        "cheerfully wanders off, knitting in hand, to rejoin",
        "crafter's haven behind to join the masses",
        "departs amid the murmured recitation of prime numbers that are 10-digits long",
        "departs, leaving behind the scent of fresh cut grass and a whimsical laugh",
        "departs, whispering a soft hymnal of thanks",
        "glances around, then pulls a book out and begins to read even as",
        "has disconnected",
        "has just left the comfort of",
        "has reconnected",
        "hurries out of the lands, muttering something about needing more tea",
        "hustles off.  Moments later, a foul stench darkens the air, lingering for entirely too long",
        "is running back to the local cafe to fuel up",
        "joins the adventure",
        "leaves, feral wails sound off in the distance",
        "library and joined the rest of the world",
        "meanders in, the scent of fresh coffee and muffins swirling along with",
        "meanders out, the scent of coffee and muffins swirling along with",
        "pulls out a bosun's whistle as",
        "pulls out a pair of knitting needles",
        "quickly tucks a bosun's whistle out of view as",
        "returns home from a hard day of adventuring",
        "slips into the area with all the grace and subtleness of a welcoming summer breeze",
        "stumbles in with a mighty yawn",
        "stumbles into the lands, desperately clutching",
        "surroundings and quickly puts the book away",
        "wake, sunset-kissed autumn leaves mark the departure of",
        "wanders in, bowing with a flourish and mocking grin to an unseen crowd",
        "wanders off in a cacophony of whirring and clanking",
        "wanders off murmuring something about a pillow and much needed sleep",
        "wanders off to take solace in",
        "wanders off towards unknown carousing calls in the distance",
        "wanders off, the faint scent of tea and citrus lingers momentarily in the air"
    ]

    static let death: [String] = [
        "CRASH*  *CLANG*  Sounds like",
        "How does one drown in a pot of tea?  Ask",
        "Looks like time's run out for",
        "Quick!  Someone loot",
        "Turns out quicksand *was* something",
        "died again",
        "even have that lever",
        "forgot how important it is to keep the blood inside",
        "fought the sea, and the sea won",
        "found out why some texts are restricted",
        "found the cure for insomnia",
        "has been smashed beneath a pile of",
        "has fallen... again!  Quick, find the body before the toadstools take over",
        "ignored several red flags",
        "in fact, could not handle it",
        "is either being melodramatic or",
        "just lost a bet with the Arkati again.  Hope Lorminstra's in a good mood",
        "not know to stay on the mount when jousting?  Trampled again",
        "should not have finished that incantation",
        "still needs a bit of tempering",
        "wasn't wearing plot armor",
        "would find a way to die again"
    ]
}
